### ISSUE TITLE
Add Traffic Monitor to Instances

### ISSUE THREAD

**Issue by owah** [jawr/kontrolvm#5]
Users should be able to see howmuch upload/download/totals they generated, with the possibility to be alarmed by email if they pass a certain amount of MB/GB (softlimit) and the possibility to have the VM forcefully suspended if they pass a preconfigured limit (hardlimit)

**Comment by jawr** [comment]
Partial implementation of this using iptables. However, having issues with python-iptables which is making it a little bit unstable at the moment.
