### ISSUE TITLE
Hypervisor settings

### ISSUE THREAD

**Issue by owah** [jawr/kontrolvm#6]
The maximum diskspace should ask for an int value, not a dropdown menu.

**Comment by jawr** [comment]
At the moment this is set to a maintainable drop down list. Use the Django admin to add new/different size. This might be pre populated using fixtures. I think it should be only editable by super admins to maintain order and consistency. 

Should definitely be ordered in a better way.

**Comment by jawr** [comment]
Changed to order this by Size (lowest to highest).
